---
title: "Autocycler benchmark"
date: "2025-04-15"
author: "Ryan Wick"
output:
  html_document:
    pandoc_args: ["+RTS", "-K64m", "-RTS", "--self-contained",]
    df_print: paged
    keep_md: false
    toc: true
    toc_float: true
    code_folding: hide
---

```{r}
library(tidyverse)
library(knitr)
library(cowplot)
library(readxl)

opts_chunk$set(dpi=300, fig.path='plots/', echo=TRUE, dev=c('png','pdf'), warning=FALSE, message=FALSE)
pdf.options(useDingbats = FALSE)
```


```{r load_data}
df <- read_excel("tables.xlsx", sheet="Assembly results")

df$`Total error count` <- df$`Error count` + df$`Extra assembly bases` + df$`Missing assembly bases`

df$Assembler <- factor(df$Assembler, levels = c("Canu", "Flye", "LJA", "metaMDBG", "miniasm", "NECAT", "NextDenovo", "Raven", "Wtdbg", "Dragonflye", "Hybracter", "MAECI", "Autocycler", "Autocycler-curated"))
```


```{r plot, fig.width = 9, fig.height = 7}
y_breaks <- c(0, 10, 100, 1000, 10000, 100000, 1000000)
y_minor_breaks <- c(seq(0, 10),
                    seq(20, 100, 10),
                    seq(200, 1000, 100),
                    seq(2000, 10000, 1000),
                    seq(20000, 100000, 10000),
                    seq(200000, 1000000, 100000))
y_labels <- c("0", "10", "100", "1k", "10k", "100k", "1M")

x_axis_labels <- function(x) {
  x <- as.character(x)
  x[x == "metaMDBG"] <- "meta-\nMDBG"
  x[x == "NextDenovo"] <- "Next-\nDenovo"
  x[x == "Dragonflye"] <- "Dragon-\nflye"
  x[x == "Hybracter"] <- "Hy-\nbracter"
  x[x == "Autocycler"] <- "Auto-\ncycler\n(auto-\nmated)"
  x[x == "Autocycler-curated"] <- "Auto-\ncycler\n(curated)"
  x
}

assembler_type <- function(x) {
  factor(case_when(
    x %in% c("Canu", "Flye", "LJA", "metaMDBG", "miniasm", "NECAT", "NextDenovo", "Raven", "Wtdbg") ~ "Single-tool\nassembly",
    x %in% c("Dragonflye", "Hybracter") ~ "Assembly\npipeline",
    x %in% c("MAECI", "Autocycler", "Autocycler-curated") ~ "Consensus\nassembly"
  ), levels = c("Single-tool\nassembly", "Assembly\npipeline", "Consensus\nassembly"))
}

assembler_type_colours <- c("Single-tool\nassembly" = "#8da0cb",
                            "Assembly\npipeline"    = "#fc8d62",
                            "Consensus\nassembly"   = "#66c2a5")

p1 <- ggplot(df, aes(x = Assembler, y = `Error count`, fill = assembler_type(Assembler))) +
  geom_boxplot(coef = Inf) +
  scale_y_continuous(trans = scales::pseudo_log_trans(base = 10), expand = c(0, 0), limits = c(0, 100000),
                     breaks = y_breaks, minor_breaks = y_minor_breaks, labels = y_labels) +
  scale_x_discrete(labels = x_axis_labels) +
  scale_fill_manual(values = assembler_type_colours) +
  theme_bw() +
  theme(axis.ticks.x = element_blank(), panel.grid.minor = element_line(size = 0.1),
        legend.key.height = unit(2.5, "lines")) +
  guides(fill = guide_legend(title = NULL)) +
  labs(title="Sequence errors (substitutions and indels)", x=NULL, y="Errors per assembly")

p2 <- ggplot(df, aes(x = Assembler, y = `Total error count`, fill = assembler_type(Assembler))) +
  geom_boxplot(coef = Inf) +
  scale_y_continuous(trans = scales::pseudo_log_trans(base = 10), expand = c(0, 0), limits = c(0, 1000000),
                     breaks = y_breaks, minor_breaks = y_minor_breaks, labels = y_labels) +
  scale_x_discrete(labels = x_axis_labels) +
  scale_fill_manual(values = assembler_type_colours) +
  theme_bw() +
  theme(legend.position = "none", axis.ticks.x = element_blank(), panel.grid.minor = element_line(size = 0.1)) +
  labs(title="Total errors (sequence errors + missing bases + extra bases)", x=NULL, y="Errors per assembly")

plot_grid(p1, p2, ncol=1, rel_heights=c(0.87, 1), align="v")
```


```{r missing_extra_plots, fig.width = 9, fig.height = 7}
p1 <- ggplot(df, aes(x = Assembler, y = `Missing assembly bases`, fill = assembler_type(Assembler))) +
  geom_boxplot() +
  scale_y_continuous(trans = scales::pseudo_log_trans(base = 10), expand = c(0, 0), limits = c(0, 1000000),
                     breaks = y_breaks, minor_breaks = y_minor_breaks, labels = y_labels) +
  scale_x_discrete(labels = x_axis_labels) +
  scale_fill_manual(values = assembler_type_colours) +
  theme_bw() +
  theme(axis.ticks.x = element_blank(), panel.grid.minor = element_line(size = 0.1),
        legend.key.height = unit(2.5, "lines")) +
  guides(fill = guide_legend(title = NULL)) +
  labs(title="Missing bases", x=NULL, y="Errors per assembly")

p2 <- ggplot(df, aes(x = Assembler, y = `Extra assembly bases`, fill = assembler_type(Assembler))) +
  geom_boxplot() +
  scale_y_continuous(trans = scales::pseudo_log_trans(base = 10), expand = c(0, 0), limits = c(0, 1000000),
                     breaks = y_breaks, minor_breaks = y_minor_breaks, labels = y_labels) +
  scale_x_discrete(labels = x_axis_labels) +
  scale_fill_manual(values = assembler_type_colours) +
  theme_bw() +
  theme(legend.position = "none", axis.ticks.x = element_blank(), panel.grid.minor = element_line(size = 0.1)) +
  labs(title="Extra bases", x=NULL, y="Errors per assembly")

plot_grid(p1, p2, ncol=1, align="v")
```

```{r autocycler_error_counts}
df %>%
  filter(Assembler == "Autocycler") %>%
  summarise(
    min = min(`Error count`, na.rm = TRUE),
    median = median(`Error count`, na.rm = TRUE),
    max = max(`Error count`, na.rm = TRUE)
  )
```